on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string

      registry_name:
        required: true
        type: string

      chart_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ inputs.app }}
    steps:
      - name: Teste Neo
        run: |
          echo "matrix registry_name > ${{ inputs.registry_name }}, chart_path > ${{ inputs.chart_path }}, app > ${{ inputs.app }}"