name: Teste Dependente

on:
  workflow_run:
    workflows: ["Teste da Matrix"]
    types: 
      - completed

jobs:
  triggado:
    runs-on: ubuntu-latest
    steps:
      - id: print-success
        run: | 
          echo "SUCESSO! > ${{github.event}}"