name: Teste Dependente

on:
  workflow_run:
    workflows: 
      - MatrixTest

jobs:
  triggado:
    runs-on: ubuntu-latest
    steps:
      - id: print-success
        run: | 
          echo "SUCESSO! > ${{github.event}}"